### ISSUE TITLE
Fix PDF Template (italian translation)

### ISSUE THREAD

**Issue by thedos1701** [thedos1701/OpenGenfri#26]
Need FIX for PDF template

**Comment by NonnEmilia** [comment]
@thedos1701 * `Customer name`
* `Customer ID`
* `Date`
* The date itself
* `Total`
* Number/value format (`,` as a decimal separator, `€` or `&euro;`)

**Comment by thedos1701** [comment]
We should use the i18n subsystem for translations, but that requires way more time
