### ISSUE TITLE
Add a little style to every page

### ISSUE THREAD

**Issue by thedos1701** [thedos1701/OpenGenfri#27]
whatever you want, but just a more fancy page

**Comment by thedos1701** [comment]
We need a base template, from which we'll inherit everything (besides order page)
And we need la landing page other than the one attached
![screen shot 2015-07-12 at 12 59 39](https://cloud.githubusercontent.com/assets/10158962/8637532/13fc3af6-2896-11e5-87d6-0faba8daae33.png)

**Comment by radome** [comment]
It would be nice to have "Go Back" buttons in the backend pages or a link to the order page.
This because the application should be usable run fullscreen mode.
