### ISSUE TITLE
JS calculator in order page

### ISSUE THREAD

**Issue by thedos1701** [thedos1701/OpenGenfri#30]
It would be nice to add a javascript calculator to the order page

(low priority)

**Comment by NonnEmilia** [comment]
I have some doubts on this. Genfri (the human one) told me that a calculator or anything like this is useless and it only slow down the workflow.

I don't know if i's a good idea to re-implement a calculator in JavaScript in an already complicated page like that.

**Comment by NonnEmilia** [comment]
A simpler way is to implement #52.
