### ISSUE TITLE
More readable PDF

### ISSUE THREAD

**Issue by NonnEmilia** [thedos1701/OpenGenfri#32]
Could be better create a more clean and readable PDF.

Prices are useful for the customer, not for the cooks.

The customer should have a complete and exhaustive copy, the cooks need only quantities and table/name. (That implies also freeing some space for a bigger font)

**Comment by thedos1701** [comment]
Will do

**Comment by thedos1701** [comment]
BTW They need Quantity, table name and timestamp, to avoid re-using of bills

**Comment by thedos1701** [comment]
__NEVER__TRUST__ANYONE__
