### ISSUE TITLE
Error prompt on negative total

### ISSUE THREAD

**Issue by radome** [thedos1701/OpenGenfri#60]
The bill is committed correctly on the DB but the page prompts an error instead of printing the bill.
![screen shot 2015-07-19 at 2 27 29 pm](https://cloud.githubusercontent.com/assets/1145093/8765981/bdbb46cc-2e27-11e5-9e0f-b4742e74d7f5.JPG)

**Comment by NonnEmilia** [comment]
In dbmanager.py the function commit_bill set correctly total at 0 for the dbhandler. Should be done the same for the output, that is passed back to the frontend as a JSON object.

**Comment by radome** [comment]
Yup
